openapi: 3.0.0
info:
  version: 1.0.0
  title: orb-fleet
servers:
  - url: 'http://localhost:8203'
paths:
  /agents:
    post:
      summary: 'Create new Agent'
      operationId: createAgent
      tags:
        - agent
      requestBody:
        required: true
        content:
            application/json:
                schema:
                    type: object
                    properties:
                        name:
                            type: string
                        orb_tags:
                            type: object
      responses:
        '200':
          description: 'Agent add details including key, shown only once'
          content:
            application/json:
              schema:
                type: object
                properties:
                    id:
                        type: string
                        format: uuid
                    name:
                        type: string
                    key:
                        type: string
                        format: uuid
                    channel_id:
                        type: string
                        format: uuid
                    state:
                        type: string
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Agent:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string