# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: "Behave Tests"

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '30 5,17 * * *'
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
               python -m pip install --upgrade pip
               pip install -r python-test/requirements.txt
      - name: Run orb
        run: make run
      - name: Make test_config.ini
        run: |
          echo "[test_config]" > python-test/test_config.ini
          echo "email=testuser@orb.live" >> python-test/test_config.ini
          echo "password=testpass" >> python-test/test_config.ini
          echo "orb_address=localhost" >> python-test/test_config.ini
          echo "ignore_ssl_and_certificate_errors=True" >> python-test/test_config.ini
          echo "agent_docker_tag=develop" >> python-test/test_config.ini
      - name: Run behave
        working-directory: ./python-test
        run: behave
