openapi: 3.0.0
info:
  version: 1.0.0
  title: orb-sinks
servers:
  - url: 'http://localhost:8200'
paths:
  /sinks:
    get:
      summary: 'List Sinks'
      operationId: listSinks
      tags:
        - sink
      responses:
        '200':
          description: 'One page of Sink details'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sink'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: 'Create new Sink'
      operationId: createSink
      tags:
        - sink
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                config:
                  type: object
      responses:
        '200':
          description: 'Sink add details'
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  name:
                    type: string
                  config:
                    type: object
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /features/sinks:
    get:
      summary: 'List Sink backends and feature sets'
      operationId: sinkFeatures
      tags:
        - sink
      responses:
        '200':
          description: 'Sink feature details'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SinkBackend'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    ConfigEntry:
      type: object
      properties:
        title:
          type: string
          description: Visual title of the config item shown in UI
        type:
          type: string
          description: "Data field type, one of 'string' or 'int'"
        name:
          type: string
          description: The field label used in the JSON config object for this field
        description:
          type: string
          description: A description of the use of this configuration field
      example:
        title: Remote Host
        type: string
        name: remote_host
        description: The remote host to send Prometheus metrics toop
    Sink:
      type: object
      required:
        - id
      properties:
        id:
          type: string
    SinkBackend:
      type: object
      properties:
        backend:
          type: string
          example: prometheus
          description: Name and identifier of the sink backend, used when creating new sinks
        description:
          type: string
          example: Prometheus time series database sink
        config:
          type: array
          description: Backend configuration field details
          items:
            items:
              $ref: '#/components/schemas/ConfigEntry'
    Error:
      type: object
      properties:
        message:
          type: string